spring:
  datasource:
    url: jdbc:mysql://mysql:3306/tasks
    username: root
    password: lgl99VICTOR99@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
